[build]
  publish = "public"  # Change this if your HTML file is in a different directory
  command = "npm run build"  # Optional, only if you have a build command

[[redirects]]
  from = "/templates"
  to = "/index.html"
  status = 200
