services:
  - type: web
    name: reviewanalyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn App:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    packages:
      - google-chrome-stable
      - chromium-chromedriver
